<h5>Evaluación de políticas y programas públicos</h5>

<p>La evaluación se define como aquella actividad que permite valorar el desempeño de la acción pública, sea en la forma de un programa, proyecto, ley, política sectorial, etc. La evaluación corresponde a una valoración sistemática de la concepción, la puesta en práctica y los resultados de una intervención pública en curso o ya concluida; o una valoración ex ante, en la fase de diseño.</p>

<p>Desde una perspectiva instrumental, la evaluación puede ser definida como un sistema conformado por un conjunto de procedimientos técnicos utilizados para la obtención, procesamiento y análisis de información relevante. Su valor en el ámbito público radica en asegurar información veraz, pertinente, útil y consistente que permita en lo interno: orientar la asignación presupuestaria, cautelar la calidad del gasto y la definición de nuevas prioridades de programas, como también fortalecer la formulación e implementación de la intervención pública. Y en lo externo, contar con elementos suficientes para responder de manera simultánea a las demandas de los ciudadanos por mayor transparencia en la acciónar pública y rendición de cuentas. En tal sentido, la evaluación y los mecanismos de control y rendición de cuentas debieran llenar de contenido estratégico el diseño e implementación de políticas públicas, la gestión pública y la calidad analítica de la decisión gubernamental.</p>

<p>La actividad de evaluación se puede plantear como una valoración en tres niveles articulados del quehacer público: macro (evalúa las prioridades políticas de largo y mediano plazo), meso (se enfoca a evaluar la política sectorial e intersectorial de mediano plazo, y la institucionalidad pública que la opera) y micro (se centra en la medición de procesos de gestión y desempeño de corto plazo).</p>

<p>Definida de esta manera, la evaluación se convierte en un mecanismo articulador y transversal, pues tiene el potencial de vincular los contenidos de formulación de las políticas públicas con su implementación, con la gestión de los recursos y los efectos sociales, y además, refleja la interacción entre los distintos sectores de gobierno. También, posibilita la interacción entre los sectores de gobierno más general (presidencia, finanzas, planificación, etc.) y los específicos (salud, obras públicas, vivienda, etc.), a través de análisis que exploran y construyen información de diversas fuentes y enfoques sobre la intersectorialidad en el ejercicio de las políticas públicas para ciertos programas o estrategias de desarrollo (protección social, fomento productivo, por ejemplo), la coordinación entre las diferentes instituciones públicas, entre las regiones y los niveles de gobierno (central, sectorial, estatal municipal), y con la sociedad civil.</p>

<p>Estado y las políticas públicas tienen un rol decisivo que cumplir en los objetivos de transformación productiva con equidad, lo que requiere una mayor efectividad de las políticas sociales, con la generación de valor público. Para asegurar este propósito, las funciones de evaluación y planificación deben formar parte de un mismo sistema, que opere de manera sincrónica, entre el uso de los recursos públicos, la calidad de lo que se produce con esos recursos y los resultados que se logran. </p>

